# docker-compose.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: trustlesswork-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: indexer123
    ports:
      - "15432:5432"   # <-- usa 15432 en el host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer -d indexer"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
